name:  Reporte de bug
description: Reporta un bug del proyeto
title: "Bug:"
labels: ["Reporte de bug", "status: esperando revisi贸n"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Descripci贸n del bug 
      placeholder: Describe el bug encontrado 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento esperado
      placeholder: Describe que esperabas que pasara 
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Comportamiento real
      placeholder: Describe que paso realmente 
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: Acepto el c贸digo de conducta del proyecto
          required: true
        - label: Quiero trabajar en esta funci贸n
